apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ansible-awx.fullname" . }}
  labels:
    app: {{ template "ansible-awx.name" . }}
    chart: {{ template "ansible-awx.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{ if .Values.adminPassword }}
  awx-admin-password: {{ .Values.adminPassword | b64enc | quote }}
  {{ else }}
  awx-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.secretkey }}
  awx-secretkey: {{ .Values.secretkey | b64enc | quote }}
  {{ else }}
  awx-secretkey: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}

