apiVersion: v1
kind: Service
metadata:
  name: {{ template "ansible-awx.fullname" . }}
  labels:
    app: {{ template "ansible-awx.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8052
      protocol: TCP
  selector:
    app: {{ template "ansible-awx.name" . }}
    release: {{ .Release.Name }}
